### ISSUE TITLE
Bump to 1.0.0?

### ISSUE THREAD

**Issue by naholyr** [kevinbeaty/fs-promise#12]
Hello, this library seems widely used, has no issue… Wouldn't it be time to allow proper semantic versionning by bumping version to 1.0.0?

**Comment by kevinbeaty** [comment]
Yup, good idea.

I was waiting for a `1.0.0` of `fs-extra`  which seemed to be coming soon just in case there was a quick major bump required for that compatibility.  But maybe I should just bite the bullet.

**Comment by RyanZim** [comment]
@kevinbeaty I'm a collaborator at `fs-extra`. v1.0.0 should be coming out this weekend, if all goes well. v1.0.0 will include a few breaking changes.

**Comment by RyanZim** [comment]
fs-extra v1.0.0 is shipped!

**Comment by kevinbeaty** [comment]
Published 1.0.0
