### ISSUE TITLE
What is "file" in example snippet

### ISSUE THREAD

**Issue by vprasanth** [kevinbeaty/fs-promise#13]
Hey there, regarding this snippet from the README:

```javascript
fsp.writeFile(file('hello1'), 'hello world')
  .then(function(){
    return fsp.readFile(file('hello1'), {encoding:'utf8'});
  })
  .then(function(contents){});
```

What is `file`? Sorry if this is ultra noob.

**Comment by kevinbeaty** [comment]
Sorry for the confusion, I must have copied the example from my tests.  It's just a function that returns a file path as a string, e.g. `'/tmp/hello1'`. 

All functions proxy either Node.js `fs` or `fs-extra` (in this case [`writeFile`](https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback) directly only returning promises instead.
