### ISSUE TITLE
Does not promisify mkdtemp

### ISSUE THREAD

**Issue by futpib** [kevinbeaty/fs-promise#24]
```
> require('fs-promise').mkdtemp('test')
undefined // expected Promise
```

**Comment by RyanZim** [comment]
@futpib What version of `fs-promise` are you using? Also, what Node.js version are you using?

**Comment by futpib** [comment]
@RyanZim
node v7.7.4
fs-promise 2.0.1

**Comment by RyanZim** [comment]
Confirmed. This issue should be moved to https://github.com/normalize/mz, since they handle promisifying the native `fs` methods. Would you mind doing that for me? Thanks!

**Comment by futpib** [comment]
Well, It is apparent [from sources](https://github.com/kevinbeaty/fs-promise/blob/feff506/index.js#L38) that fs-promise does not reexport mkdtemp.

Also
```js
> require('mz/fs').mkdtemp('test')
Promise { <pending> }
```

**Comment by RyanZim** [comment]
Oh sorry, didn't realize we had such a brittle approach to this. I'll try and fix this tonight.

**Comment by kevinbeaty** [comment]
Version 2.0.2 Published.  Thanks!
