### ISSUE TITLE
Walk removed?

### ISSUE THREAD

**Issue by MarcoThePoro** [kevinbeaty/fs-promise#28]
Hey, the readme for the project still says that that project proxies `walk` from fs-extra, but `walk` was removed in fs-extra 2.0.0.

Do you still intend to support `walk`? fs-extra moved it into its own package [klaw](https://github.com/jprichardson/node-klaw)

**Comment by RyanZim** [comment]
@MarcoThePoro Hey, thanks for the catch! I didn't realize the README still mentioned `walk`. `fs-promise` does not support it; we just didn't correctly update the docs. Care to submit a PR removing it from the readme?

**Comment by MarcoThePoro** [comment]
Yeah sure
