### ISSUE TITLE
Deprecate in favor of fs-extra v3

### ISSUE THREAD

**Issue by RyanZim** [kevinbeaty/fs-promise#30]
fs-extra v3 was just released with native promise support.

Here's the changelog: https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md#300--2017-04-27

Switching should be pretty easy, but there's a few gotchas:

- fs-extra v3 doesn't use any-promise; only native promises are supported
- fs-promise uses mz/fs which fixes the callback signature for `fs.exists`. fs-extra is a drop-in replacement for the native fs, so we can't fix that. fs-extra v3 adds a `pathExists()` method that behaves like mz/fs's `exists`.

Would like to discuss the best way to deprecate this with @kevinbeaty.

**Comment by kevinbeaty** [comment]
@RyanZim Great news.

What about creating a version 3.0.0 that basically just does this:

```js
module.exports = require('fs-extra')
```
Replacing readme with deprecation in favor of note, and marking deprecated in npm?

**Comment by RyanZim** [comment]
Why bother? Just change add a deprecation note to the top of the README, push a patch version to update the README on npm, and npm deprecate all versions IMO.

**Comment by kevinbeaty** [comment]
I dunno, closure I guess ;)

Sure, that works

**Comment by RyanZim** [comment]
Whatever, IDC

**Comment by kevinbeaty** [comment]
Haha, neither do I, it was just my first thought.  Honestly, I haven't used this package for quite a while.

I added a note to a description.  I'll likely do as you suggest later.

Anyway, thanks for all your help here and your efforts in fs-extra.

**Comment by RyanZim** [comment]
> Honestly, I haven't used this package for quite a while.

What were you using?

**Comment by kevinbeaty** [comment]
bluebird promisify. haha.  And now the secret is out.

**Comment by kevinbeaty** [comment]
I tried to deprecate a while ago ( #6 ) but promise support for fs-extra prevented that.

**Comment by kevinbeaty** [comment]
That's a wrap.  We are now officially deprecated.

Thanks again for the help @RyanZim
