### ISSUE TITLE
Consider deprecation in favor of mz

### ISSUE THREAD

**Issue by kevinbeaty** [kevinbeaty/fs-promise#6]
normalize/mz#16 now incorporates `any-promise`.   Consider deprecating `fs-promise` in favor of `mz/fs`

**Comment by jonathantneal** [comment]
I love this repo, and I use for anything filesystem related, so I want to track this repo.

**Comment by kevinbeaty** [comment]
@jonathantneal Thanks for the feedback.  Don't worry, I'm not in a hurry to deprecate `fs-promise`, and there probably is little reason to since it is such a limited scope with little maintenance.

But I am curious to hear why you prefer `fs-promise` over moving to [`mz`](https://github.com/normalize/mz/).  It seems like most things would work if you swap `var fsp = require('fs-promise')` to `var fsp = require('mz/fs')`.

Is it only because you use it with `fs-extra`?  (I saw your note on #5) Or are there other reasons?

**Comment by jonathantneal** [comment]
I was on vacation, sorry for the delay. Yes, I do use this almost exclusively with `fs-extra`, but I started having issues where [some users would not get `fs-extra`](https://github.com/jonathantneal/mdcss/issues/12), so I had to include [my own version](https://github.com/jonathantneal/mdcss/blob/master/lib/fs-promise.js) that explicitly called `fs-extra`.

**Comment by kevinbeaty** [comment]
I'm again thinking of deprecating this module:

For normal `fs` one could use [`mz`](https://github.com/normalize/mz/).
For `fs-extra` you could use [`fs-extra-promise`](https://github.com/overlookmotel/fs-extra-promise)

Or your favorite `promisify`/`thenify` wrapper in either case.

**Comment by jonathantneal** [comment]
bummer. I don’t want to get near bluebird.

**Comment by kevinbeaty** [comment]
Most of my needs are covered with `mz`.   And after realizing the issue with #7 should likely be solved using something like [`thenify`](https://github.com/thenables/thenify), this module would basically be equivalent in API (and implementation) to `mz/fs`.

The only exception would be for `fs-extra` support  in #5 (and potentially TypeScript declarations as mentioned by @olivr70 in #7 ).

I could see this evolve into an alternative to `fs-extra-promise` backed by `any-promise`.  If that is appealing, would you be willing to submit a PR?  (Or even be added as a maintainer?)  Seems like you are already most of the way there with your custom implementation.

**Comment by jonathantneal** [comment]
If you end up accepting that other pull request, we can probably close this issue.

**Comment by kevinbeaty** [comment]
@jonathantneal OK. You've convinced me :)  I'll close this issue.  Thanks for your help and interest.
