### ISSUE TITLE
write() callback third argument is not passed

### ISSUE THREAD

**Issue by olivr70** [kevinbeaty/fs-promise#7]
Hi,

fs-promise very interesting to avoid callback hell. I am new to node and Promises, so may be I missed something. 

The implementation of fs-promise is very clever, but I think its global approach fails with the write() function.

As stated in the doc, write() **cb** argument takes 3 arguments : err, written and data.
This 3rd argument is not passed to the .then handler (see example below)

Because of the Promise spec, I believe the promise value should be a single object with written and data/buffer properties. But this means handling a special case in fs-promise.

By the way, do you know of any typescript binding for fs-promise. I am ready to write one if none exists, and ideally would like to add it directly into the fs-promise project.

Olivier

``` Javascript
function testWriteFsp() {
  fsp.open("some.txt", "w+").then( function (fd) {
    return fsp.write(fd, "hello fs-promise").then( function (written, text) {
      console.log(written,"/",text);
      return fsp.close(fd);
    })
  }).catch( function (reason) {
    console.log("Unable to write to file ",reason);
  })
}
// 16/undefined
```

**Comment by kevinbeaty** [comment]
Nice catch.  Honestly, I've never noticed the third argument to the callback before now.  I think you are right, it would probably be good to special case `write` to resolve the promise with an array of `[written, data]`.

> By the way, do you know of any typescript binding for fs-promise. I am ready to write one if none exists, and ideally would like to add it directly into the fs-promise project.

I'm not too familiar with TypeScript, but I would accept a PR if the type definitions can be included without requiring TypeScript in the implementation.

**Comment by kevinbeaty** [comment]
@olivr70 I'm considering again deprecating this module see #6 

You may be interested in [`mz/fs`](https://github.com/normalize/mz/).  It looks like it handles passing multiple callback arguments to the resolved promise.

**Comment by olivr70** [comment]
@kevinbeaty Thanks for the quick reply

I just looked at mz/fs and it looks to be a good superset of fs-promise. It has no Typescript type definition either.

For my needs, mz/fs also looks to be sufficient, and solves de multiple callback arguments issue. I will look into it.

Thanks again, and I really found your implementation smart and concise.

**Comment by kevinbeaty** [comment]
@olivr70 I've been convinced by @jonathantneal to keep `fs-promise` around as a "promisified" `fs-extra`.  Are you interested in adding TypeScript support or addressing the issue with multiple callback arguments?

I believe a good way to address the multiple callback arguments would be to use either [`thenify`](https://github.com/thenables/thenify) or [`thenify-all`](https://github.com/thenables/thenify-all).  You can look at `mz/fs` for an example of use.  The functions are now listed explicitly after merging #8 , so this should be a relatively easy change.

The TypeScript support would be up to you if you are interested :)

**Comment by kevinbeaty** [comment]
Multiple callback arguments handled by `thenify-all` and `mz` dependency added in #11 .  Feel free to open a new issue/PR for TypeScript if that is still desired.
